# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaopei', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Question_audio',
        ),
    ]
