# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaopei', '0002_auto_20180829_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('talkWord', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question_audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audioUrl', models.CharField(max_length=50)),
                ('wavname', models.CharField(default=b'none', max_length=50)),
            ],
        ),
    ]
